apiVersion: v1
kind: ServiceAccount
metadata:
  name: mise-deployer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mise-deployer-role
rules:
  - apiGroups: ["", "apps", "batch", "networking.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mise-deployer-binding
subjects:
  - kind: ServiceAccount
    name: mise-deployer
    namespace: default
roleRef:
  kind: ClusterRole
  name: mise-deployer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mise-deployer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mise-deployer
  template:
    metadata:
      labels:
        app: mise-deployer
    spec:
      serviceAccountName: mise-deployer
      containers:
        - name: runner
          image: debian:bookworm-slim
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e

              echo "Installing dependencies..."
              apt-get update
              apt-get install -y curl git ca-certificates gnupg

              echo "Installing mise..."
              curl https://mise.run | sh
              export PATH="/root/.local/bin:$PATH"

              echo "Cloning repository..."
              git clone https://github.com/Pumahawk/simpl-agents-controller.git /app
              cd /app

              echo "Running mise install..."
              mise trust
              mise install

              echo "Starting loop..."
              while true; do
                mise run environment:remote_update_all
                sleep 300
              done
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
